- name: Modificacion docker.service para insecure registry
  hosts: all
  tasks: 
    - name: "Sustituir línea a docker service"
      lineinfile: 
        path: /lib/systemd/system/docker.service
        regexp: '^ExecStart'
        line: 'ExecStart=/usr/bin/dockerd -H fd:// --insecure-registry osiris:8123'
    - name: "Restart Servicio Docker"
      service: 
        name: docker
        daemon_reload: yes
        state: restarted